### PR TITLE
jaxlib 0.3.10 with cuda 11.2

### LINKED ISSUE #34: JAX with GPU support
It would be a huge benefit if the JAX condaforge package would come precompiled for GPU and automatically install the necessary packages for GPU support. From my understanding, cudnn and cudatoolkit from the TF 2.2 package should work and if nvcc is needed, it's available in cudatoolkit-dev. This would remove the requirement for a system-wide CUDA installation and allow usage in isolated environments. Would probably also be hugely beneficial for Windows users who want to use JAX on GPU.

Thanks to all!

### PR DESCRIPTION
**Pull request by ngam**
Closes #100 
Fix #34 
Closes #72 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
This is also ready for review. Same as PR #100 except jaxlib 0.3.10 instead of 0.3.7

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by xhochy** [comment]
Can you please add the `__cuda` requirement to `run`?

**Review by ericmjl — APPROVED** [review]

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by xhochy** [comment]
@ngam Seems like #100 fails reliably whereas this one only fails for the usual OSX SDK downloads. Thus when this turns green, I would merge it and close #100; or are you interested in also getting #100 merged?

**Comment by ngam** [comment]
> @ngam Seems like #100 fails reliably whereas this one only fails for the usual OSX SDK downloads. Thus when this turns green, I would merge it and close #100; or are you interested in also getting #100 merged?

No, I don't care about #100. I am fine with merging this only. One of us will likely have to keep a close eye on these going forward to ensure they all get to green one way or another.

**Pull request merged**
