### PR TITLE
Bump cudnn to 9

### PR DESCRIPTION
**Pull request by traversaro**
Test if compilation works, waiting for https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6310, useful to fix https://github.com/conda-forge/jax-feedstock/issues/149 and https://github.com/conda-forge/jaxlib-feedstock/issues/277 .

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
After rerenderign the linux build disappeared, probably it is related to cirun?

**Comment by traversaro** [comment]
The current macos builds are not useful, closing the PR so hopefully they will stop.

**Comment by h-vetinari** [comment]
> I am not sure if [the approved list](https://raw.githubusercontent.com/Quansight/open-gpu-server/main/access/conda-forge-users.json) is open for anyone to join, so if there's a place to request access, I'd be happy to join

Yes, you can join, if you follow the [instructions](https://github.com/Quansight/open-gpu-server/#access) on that repo.

**Comment by traversaro** [comment]
> @traversaro any objections before we merge?

No objections on my side, thanks a lot for handling this!

**Comment by xhochy** [comment]
I would prefer to merge #279 if it passes straight-away.

**Pull request closed without merging**
