### PR TITLE
All builds

### PR DESCRIPTION
**Pull request by ocefpaf**
Add all platforms.

### CODE REVIEW

**Comment by ericmjl** [comment]
🎉!!! Thanks @ocefpaf!

**Comment by jbcaillau** [comment]
Hi all, thanks for the great job with jax & conda-forge. Seems like Jax-0.1.62 requires jaxlib-0.1.41 while jaxlib-0.1.39 is on conda-forge. I am mistaken? If not, is it please possible to update?

**Comment by ericmjl** [comment]
That's weird, seems like the bots haven't gotten an update to jaxlib=0.1.41. @ocefpaf, do you know if there was an infra change recently? jaxlib is up to 0.1.42 on PyPI now.

**Comment by ocefpaf** [comment]
I sent #20 to update it but I'm not sure why the bot did not picked that up. Investigating...

**Pull request merged**
