### PR TITLE
Ensure the XLA Function cache is built on osx

### LINKED ISSUE #62: macOS arm64 build crashes with "Symbol not found"
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Thanks for your work with the macOS arm64 build @xhochy - I'm really looking forward to getting this to work!

On my new mac, when I create a fresh environment:

```
conda create -n jaxlib-test -c conda-forge python=3.9 jax jaxlib
```

and then import `jax` (or `jaxlib.xla_client`), it fails with the following `ImportError`:

```python
Python 3.9.6 | packaged by conda-forge | (default, Jul 11 2021, 03:35:11) 
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import jax
/opt/homebrew/Caskroom/miniforge/base/envs/jaxlib-test/lib/python3.9/site-packages/jax/lib/__init__.py:31: UserWarning: JAX on Mac ARM machines is experimental and minimally tested. Please see https://github.com/google/jax/issues/5501 in the event of problems.
  warnings.warn("JAX on Mac ARM machines is experimental and minimally tested. "
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Caskroom/miniforge/base/envs/jaxlib-test/lib/python3.9/site-packages/jax/__init__.py", line 37, in <module>
    from . import config as _config_module
  File "/opt/homebrew/Caskroom/miniforge/base/envs/jaxlib-test/lib/python3.9/site-packages/jax/config.py", line 18, in <module>
    from jax._src.config import config
  File "/opt/homebrew/Caskroom/miniforge/base/envs/jaxlib-test/lib/python3.9/site-packages/jax/_src/config.py", line 27, in <module>
    from jax import lib
  File "/opt/homebrew/Caskroom/miniforge/base/envs/jaxlib-test/lib/python3.9/site-packages/jax/lib/__init__.py", line 73, in <module>
    from jaxlib import xla_client
  File "/opt/homebrew/Caskroom/miniforge/base/envs/jaxlib-test/lib/python3.9/site-packages/jaxlib/xla_client.py", line 31, in <module>
    from . import xla_extension as _xla
ImportError: dlopen(/opt/homebrew/Caskroom/miniforge/base/envs/jaxlib-test/lib/python3.9/site-packages/jaxlib/xla_extension.so, 2): Symbol not found: __ZN3jax12_GLOBAL__N_121CompiledFunctionCache16kDefaultCapacityE
  Referenced from: /opt/homebrew/Caskroom/miniforge/base/envs/jaxlib-test/lib/python3.9/site-packages/jaxlib/xla_extension.so
  Expected in: flat namespace
 in /opt/homebrew/Caskroom/miniforge/base/envs/jaxlib-test/lib/python3.9/site-packages/jaxlib/xla_extension.so
```

Do y'all have any thoughts or suggestions?

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /opt/homebrew/Caskroom/miniforge/base/envs/jaxlib-test:
#
# Name                    Version                   Build  Channel
absl-py                   0.13.0             pyhd8ed1ab_0    conda-forge
ca-certificates           2021.5.30            h4653dfc_0    conda-forge
jax                       0.2.19             pyhd8ed1ab_0    conda-forge
jaxlib                    0.1.69           py39h7f752ed_0    conda-forge
libblas                   3.9.0           11_osxarm64_openblas    conda-forge
libcblas                  3.9.0           11_osxarm64_openblas    conda-forge
libcxx                    12.0.1               h168391b_0    conda-forge
libgfortran               5.0.0.dev0      11_0_1_hf114ba7_23    conda-forge
libgfortran5              11.0.1.dev0         hf114ba7_23    conda-forge
liblapack                 3.9.0           11_osxarm64_openblas    conda-forge
libopenblas               0.3.17          openmp_h5dd58f0_1    conda-forge
llvm-openmp               12.0.1               hf3c4609_1    conda-forge
ncurses                   6.2                  h9aa5885_4    conda-forge
numpy                     1.21.2           py39h1f3b974_0    conda-forge
openssl                   1.1.1k               h3422bc3_1    conda-forge
opt_einsum                3.3.0              pyhd8ed1ab_1    conda-forge
pip                       21.2.4             pyhd8ed1ab_0    conda-forge
python                    3.9.6           h54d631c_1_cpython    conda-forge
python-flatbuffers        2.0                pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
readline                  8.1                  hedafd6a_0    conda-forge
scipy                     1.7.0            py39h5060c3b_0    conda-forge
setuptools                57.4.0           py39h2804cbe_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.36.0               h72a2b83_0    conda-forge
tk                        8.6.11               he1e0b03_0    conda-forge
tzdata                    2021a                he74cb21_1    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
xz                        5.2.5                h642e427_1    conda-forge
zlib                      1.2.11            h31e879b_1009    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : jaxlib-test
    active env location : /opt/homebrew/Caskroom/miniforge/base/envs/jaxlib-test
            shell level : 3
       user config file : /Users/dforemanmackey/.condarc
 populated config files : /opt/homebrew/Caskroom/miniforge/base/.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.6.final.0
       virtual packages : __osx=11.5.2=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /opt/homebrew/Caskroom/miniforge/base  (writable)
      conda av data dir : /opt/homebrew/Caskroom/miniforge/base/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /opt/homebrew/Caskroom/miniforge/base/pkgs
                          /Users/dforemanmackey/.conda/pkgs
       envs directories : /opt/homebrew/Caskroom/miniforge/base/envs
                          /Users/dforemanmackey/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.9.6 Darwin/20.6.0 OSX/11.5.2
                UID:GID : 1185:20
             netrc file : None
           offline mode : False
```
</details>

### PR DESCRIPTION
**Pull request by xhochy**
Fixes #62 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xhochy** [comment]
No, this is based on 0.1.71 and we already have .73 in master and also is failing the tests on `osx-arm64`, I'll have a look in the next days.

**Comment by xhochy** [comment]
This needs a rebase though!

**Comment by ocefpaf** [comment]
@conda-forge-admin please rerender

**Comment by xhochy** [comment]
If we skip `osx and arm64`, we could merge this in. We should though also mark all osx-arm64 builds as broken for now. The fixing for them is more complicated.

**Comment by ocefpaf** [comment]
> If we skip `osx and arm64`, we could merge this in. We should though also mark all osx-arm64 builds as broken for now. The fixing for them is more complicated.

Done and done. See https://github.com/conda-forge/admin-requests/pull/342

**Pull request merged**
