### PR TITLE
Statically link libprotobuf

### LINKED ISSUE #89: `jaxlib` 0.3.0 conda-forge package is broken
A user reports that the conda-forge `jaxlib` package is currently broken:

https://github.com/google/jax/issues/9643

The official `pip` packages don't seem to have this problem, so it must be something specific to the conda-forge build.

### PR DESCRIPTION
**Pull request by xhochy**
Fixes #89

### CODE REVIEW

**Comment by isuruf** [comment]
Shouldn't the license of libprotobuf be bundled then?

**Comment by xhochy** [comment]
> Shouldn't the license of libprotobuf be bundled then?

Yes, it should. Somewhere `bazel` also stores the aggregated licenses. I'm looking into that now.

**Comment by hmaarrfk** [comment]
Isn't this the use case for using a system like conda forge?

Do we know why the breakage occurs?

**Comment by xhochy** [comment]
Yes, this is a very common issue with protobuf. We statically link it because of that in some other places, too. Protobuf has a global namespace and different libraries use the same objects but in different versions. This then collides. Splitting this global namespace is easily done (and sadly the only option) by linking protobuf individually into these packages. Here it is about Tensorflow proto definitions that are loaded in the same process where we have different versions of tensorflow in the process (jaxlib is mainly a subtree from tensorflow at a certain commit, not a release). In the ONNX world we have the same where each ONNX library has different versions of the same ONNX protobuf definitons.

**Comment by xhochy** [comment]
> > Shouldn't the license of libprotobuf be bundled then?
> 
> Yes, it should. Somewhere `bazel` also stores the aggregated licenses. I'm looking into that now.

See https://github.com/conda-forge/tensorflow-feedstock/pull/213/commits/4ff3efc6a99bcdfa22b2de9d185b38bcb8c3f871 for a general solution for Tensorflow. I'll open a PR upstream and will also apply this here, too.

**Pull request merged**
