### PR TITLE
jaxlib 0.3.7 with cuda 11.2

### PR DESCRIPTION
**Pull request by ngam**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
A confirmation: py37 build from [here](https://artprodeus21.artifacts.visualstudio.com/A910fa339-c7c2-46e8-a579-7ea247548706/84710dde-1620-425b-80d0-4cf5baca359d/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2NvbmRhLWZvcmdlL3Byb2plY3RJZC84NDcxMGRkZS0xNjIwLTQyNWItODBkMC00Y2Y1YmFjYTM1OWQvYnVpbGRJZC81MDYyNjkvYXJ0aWZhY3ROYW1lL2NvbmRhX2FydGlmYWN0c18yMDIyMDUxNC4xMC4xX2xpbnV4XzY0X2NfY29tcGlsZXJfdmVyc2lvbjEwY3VkYV9jX2g0YWNiMzRhY2U40/content?format=zip) (downloaded and uploaded artifact):

```
~$ mamba list | grep jax
jax                       0.3.10             pyhd8ed1ab_0    conda-forge
jaxlib                    0.3.7           cuda112py37h592705d_1    ngam

~$ python3 -c "import jax; import jaxlib; from jax.lib import xla_bridge; print(xla_bridge.get_backend().platform); print(jaxlib.__version__); print(jax.__version__)"
gpu
0.3.7
0.3.10
```

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@xhochy pls don't bother with the other PR. Please only review this, thanks!

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Review by xhochy — APPROVED** [review]

**Comment by xhochy** [comment]
@ngam Can you switch this to using `lief_dev` as we did with tensorflow? I guess that could bring the builds faster over the finish line.

**Comment by ngam** [comment]
> @ngam Can you switch this to using `lief_dev` as we did with tensorflow? I guess that could bring the builds faster over the finish line.

Good suggestion! I will do that soon and rerender

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
Not really sure why some never work here randomly. The version of this PR for jaxlib 0.3.10 (#103), things seem to finish better...

**Review by ericmjl — APPROVED** [review]

**Pull request closed without merging**
