### PR TITLE
Abseil dual migration

### PR DESCRIPTION
**Pull request by hmaarrfk**
Needs: https://github.com/conda-forge/bazel-feedstock/pull/125

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge-admin please restart cis

**Comment by hmaarrfk** [comment]
I believe that this is ready for review. Unpinning and moving things forward seemed to work. the last I checked, there were a few failed builds before I rebased due to 400 or 404 errors.

**Comment by ngam** [comment]
Thanks, just so that I understand migrations better going forward. The idea is that one of these `grpc_cpp`s is gonna be dropped eventually?

**Comment by hmaarrfk** [comment]
yes. thought right now tensorflow can't build with the new one. So once tensorflow can, we will move it forward. It seems that 2.9.0 is a maybe.

**Comment by ericmjl** [comment]
Looks like all checks pass. I have to admit, the PR is large enough that I don't have enough bandwidth to review it in detail, so I'll defer to both of you. Should we merge?

**Comment by hmaarrfk** [comment]
I think if you trust your tests this should just be good. The commits, one at a time, are really small (except for the rerender)

**Comment by ngam** [comment]
> so I'll defer to both of you. Should we merge?

I'd vote to merge, as this doesn't change much fundamentally imo (just more variants). However, I'd give xhochy and others a few days to have a chance to look first, but also we might need to consider tf 2.9.x https://github.com/conda-forge/tensorflow-feedstock/pull/240

**Comment by ngam** [comment]
> I think if you trust your tests this should just be good

This is definitely a healthy stock. I would trust the tests to a large extent

**Comment by hmaarrfk** [comment]
xhochy has been involved in the abseil and grpc effort with me. You can ping if you want, though I presume he is just busy with other stuff.

**Review by xhochy — APPROVED** [review]

**Comment by xhochy** [comment]
Though sometimes he has time to look at this ;)

**Pull request merged**
